// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN6pgx16AkGe6OHi_bBLT_1ZpcCvrsIXc',
    appId: '1:1047241520534:web:ae398728f5e953f2a399b7',
    messagingSenderId: '1047241520534',
    projectId: 'flutter-firebase-2b89f',
    authDomain: 'flutter-firebase-2b89f.firebaseapp.com',
    storageBucket: 'flutter-firebase-2b89f.firebasestorage.app',
    measurementId: 'G-L5WB3XVQJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFsaIy5nFZUIcBwwmR5vPOfi8FmyA4CVg',
    appId: '1:1047241520534:android:ef45da1e5c889b09a399b7',
    messagingSenderId: '1047241520534',
    projectId: 'flutter-firebase-2b89f',
    storageBucket: 'flutter-firebase-2b89f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb7IUOSI1GY4LsLDzPVsf4x43oPulhRCY',
    appId: '1:1047241520534:ios:82e416e4c78009cca399b7',
    messagingSenderId: '1047241520534',
    projectId: 'flutter-firebase-2b89f',
    storageBucket: 'flutter-firebase-2b89f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN6pgx16AkGe6OHi_bBLT_1ZpcCvrsIXc',
    appId: '1:1047241520534:web:b2a63b77ee21aa8ba399b7',
    messagingSenderId: '1047241520534',
    projectId: 'flutter-firebase-2b89f',
    authDomain: 'flutter-firebase-2b89f.firebaseapp.com',
    storageBucket: 'flutter-firebase-2b89f.firebasestorage.app',
    measurementId: 'G-5ZG52MYTEK',
  );

}